### ISSUE TITLE
Google logo on sign in doesn't work

### ISSUE THREAD

**Issue by tenhobi** [tenhobi/flashcards#99]
In released app, the google logo on sigh in button doesn't appear.

**Comment by tenhobi** [comment]
Probably some issue because of `packages/...` path ?

**Comment by tenhobi** [comment]
```
I/flutter ( 3404): ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
I/flutter ( 3404): The following assertion was thrown resolving an image codec:
I/flutter ( 3404): Unable to load asset: packages/flashcards_common/assets/icons//google_logo.png
I/flutter ( 3404):
I/flutter ( 3404): When the exception was thrown, this was the stack:
I/flutter ( 3404): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
I/flutter ( 3404): <asynchronous suspension>
I/flutter ( 3404): #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:383:44)I/flutter ( 3404): <asynchronous suspension>
I/flutter ( 3404): #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:368:14)
I/flutter ( 3404): #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:86)
I/flutter ( 3404): #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82:22)
I/flutter ( 3404): #5      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:63)
I/flutter ( 3404): (elided 8 frames from package dart:async)
I/flutter ( 3404):
I/flutter ( 3404): Image provider: AssetImage(bundle: null, name:
I/flutter ( 3404): "packages/flashcards_common/assets/icons//google_logo.png")
I/flutter ( 3404): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#b22f1(), name:
I/flutter ( 3404): "packages/flashcards_common/assets/icons//google_logo.png", scale: 1.0)
I/flutter ( 3404): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by tenhobi** [comment]
@Kenny11CZ I do not know what is the real difference, maybe the usage of `Image.asset()` or the fact, that previous version had `//` in the file name. But it works now.
